version: '3.8'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bibia2806
      MYSQL_DATABASE: plataformav2

volumes:
  dbbase: