CREATE TABLE IF NOT EXISTS aula (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    cadastro DATETIME NOT NULL,
    duracao INT NOT NULL,
    imagem VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    tech VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    curso VARCHAR(255) NOT NULL
);